# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vincent Borgers
email: vincent.borgers@gmail.com
description: #> # this means to ignore newlines until "baseurl:"
  A site all about Vincent Borgers
hostmessage: Hosted on
hosturl: "https://pages.github.com/"
hostname: Github pages
thanksmessage: Thanks to
thanksurl: "https://jekyllrb.com/"
thanksname: Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vnniyb.github.io/" # the base hostname & protocol for your site
twitter_username: vnniyB
github_username:  vnniyB
linkedin_username:  vnniyB

# Build settings
markdown: kramdown

# Serving
detach:  true
port:    4000
host:    0.0.0.0

#Sitemap
gems:
  - jekyll-sitemap